version: '2'
services:

  videofaces-frontend:
    image: dsevilla/videofaces-frontend:1.0
    ports:
      - 5000:5000
    env_file: sql.env
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development


  videofaces-mysql:
    build: videofaces-mysql/.
    ports:
      - 3306
    env_file: sql.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=videofaces

  backend-rest:
    image: dsevilla/videofaces-backend-rest:1.0
    ports:
      - 8080:8080
    env_file: sql.env

  videofaces-grpc:
    image: dsevilla/videofaces-backend-grpc:1.0
    ports:
      - 50051
    env_file: sql.env

