version: '2'
services:

  flask-example:
    build:
      context: .
      dockerfile: Dockerfile-devel
    ports:
      - "5000:5000"
    volumes:
      - .:/videofaces-frontend
    user: root
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development

